"""add database indexes

Revision ID: 113bbc9d17ab
Revises: b1d2efdad70c
Create Date: 2026-08-09 15:45:49.719684

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "113bbc9d17ab"
down_revision: str | Sequence[str] | None = "b1d2efdad70c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_index(op.f("ix_products_id"), table_name="products")
    op.create_index(
        op.f("ix_products_created_at"), "products", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_products_owner_id"), "products", ["owner_id"], unique=False
    )
    op.create_index(op.f("ix_products_price"), "products", ["price"], unique=False)
    op.drop_index(op.f("ix_refresh_tokens_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_stock_movements_id"), table_name="stock_movements")
    op.create_index(
        op.f("ix_stock_movements_product_id"),
        "stock_movements",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_movements_user_id"), "stock_movements", ["user_id"], unique=False
    )
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_index(
        "ix_products_name_trgm",
        "products",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_products_name_trgm",
        table_name="products",
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.drop_index(op.f("ix_stock_movements_user_id"), table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_product_id"), table_name="stock_movements")
    op.create_index(
        op.f("ix_stock_movements_id"), "stock_movements", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_id"), "refresh_tokens", ["id"], unique=False
    )
    op.drop_index(op.f("ix_products_price"), table_name="products")
    op.drop_index(op.f("ix_products_owner_id"), table_name="products")
    op.drop_index(op.f("ix_products_created_at"), table_name="products")
    op.create_index(op.f("ix_products_id"), "products", ["id"], unique=False)
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
    # ### end Alembic commands ###
